[package]
name = "on_screen_countdown"
version = "0.1.0"
# authors = ["Your Name <you@example.com>"]
# edition = "2018"

[dependencies]
cairo-rs = { version = "0.9.0" }
gio = { version = "0.9.0" }
gtk = { version = "0.9.0" }
